apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubevirt.io: ""
  name: kubevirt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-config
  namespace: kubevirt
data:
  debug.useEmulation: "true"
  feature-gates: "LiveMigration"

