apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: cloned-datavolume
spec:
  source:
    pvc:
      namespace: default
      name: cirros
  pvc:
    accessModes:
      - ReadWriteOnce
    storageClassName: fast
    resources:
      requests:
        storage: 12Gi
